function [] = svgDrawBox(x,y,w,h)
fprintf(['',...
'<?xml version="1.0" encoding="UTF-8" standalone="no"?>\n',...
'svg\n',...
'   xmlns:dc="http://purl.org/dc/elements/1.1/"\n',...
'   xmlns:cc="http://creativecommons.org/ns#"\n',...
'   xmlns:rdf="http://www.w3.org/1999/02/22-rdf-syntax-ns#"\n',...
'   xmlns:svg="http://www.w3.org/2000/svg"\n',...
'   xmlns="http://www.w3.org/2000/svg"\n',...
'   width="300"\n',... %TODO fix this
'   height="200">\n',... %TODO also this
'  <g>\n',...
'    <path\n',...
'       style="fill:none;stroke:#000000;stroke-width:1px;stroke-linecap:butt;stroke-linejoin:miter;stroke-opacity:1"\n',...
'       d="m ',num2str(x),',',num2str(y),' ',num2str(w),',',num2str(h),'" />\n',...
'       <!-- horizonatal (R/L) offset, vertical (U/D) offset, horizontal length, vertical length -->\n',...
'  </g>\n',...
'</svg>\n',...
])
end
