function [lines] = svgDrawBox(w,text)
    lines = ['',...
    '            <rect height="20" width="',num2str(w),'" x="0" y="0"/>\n',...
    '            <text x="2" y="16">',text,'</text>\n',...
    ];
end
