function [lines] = svgMoveBox(dx,dy,lines)
    if (dx ~= 0)
    {
        lines = ['',...
        '    <g transform="translate(',str2num(dx),',0)"> <!-- Move right -->\n',...
                    lines,
        '    </g>\n',...
        ];
    }
    if (dy ~= 0)
    {
        lines = ['',...
        '        <g transform="translate(0,',num2str(dy),')"> <!-- Move down -->\n',...
                    lines,
        '        </g>\n',...
        ];
    }
end
