function [lines] = svgNewTable(x,width,rowVector)
    lines = [svgStartColumn()];
    for i=1:length(rowVector)
        lines = [lines,svgMoveBox(x,0,svgMoveBox(0,i*20,svgDrawbox(width,rowVector(i))))];
    end
    lines = [lines,svgEndColumn()];
end

function [lines] = svgTableHeader(title)
    lines = ['',...
                '<?xml version="1.0" encoding="UTF-8" standalone="no"?>\n',...
                '<!DOCTYPE svg PUBLIC "-//W3C//DTD SVG 1.1//EN" "http://www.w3.org/Graphics/SVG/1.1/DTD/svg11.dtd">\n',...
                '<svg width="100%" height="100%" xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink">\n',...
                '    <defs>\n',...
                '        <style type="text/css"><![CDATA[\n',...
                '        text{\n',...
                '            font: 12px Verdana, Helvetica, Arial, sans-serif;\n',...
                '            text-anchor: start;\n',...
                '        }\n',...
                '        rect{\n',...
                '            stroke: black;\n',...
                '            stroke-width: 1;\n',...
                '            fill: none;\n',...
                '        }\n',...
                '        ]]></style>\n',...
                '    </defs>\n',...
                '    <title>',title,'</title>\n',...
                ];
end
